apiVersion: batch/v1
kind: Job
metadata:
  name: db-prime
spec:
  template:
    spec:
      containers:
        - name: fdw-grants
          image: docker.bundlepledge.com/catarse-deploy/core-db
      imagePullSecrets:
        - name: regcred
