apiVersion: apps/v1
kind: Deployment
metadata:
  name: catarse-db
spec:
  template:
    spec:
      containers:
        - name: catarse-db
          image: docker.bundlepledge.com/catarse-deploy/catarse-db
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catarse-moments-db
spec:
  template:
    spec:
      containers:
        - name: catarse-moments-db
          image: docker.bundlepledge.com/catarse-deploy/moments-db
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-core-db
spec:
  template:
    spec:
      containers:
        - name: service-core-db
          image: docker.bundlepledge.com/catarse-deploy/core-db
      imagePullSecrets:
        - name: regcred
