persistence:
  enabled: true
  storageClass: linode-block-storage
  size: 60Gi
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 30720m
  tls: 
    - hosts:
      - docker.bundlepledge.com
      secretName: bundle-pledge-docker-tls
  hosts:
    - docker.bundlepledge.com